swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /Version:
    # our controller name
    x-swagger-router-controller: propa
    get:
      description: get dll version
      operationId: Version
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OkResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
          
  /clima/Rain_Intensity:
    # our controller name
    x-swagger-router-controller: propa
    get:
      description: Rain Intensity (mm/h)
      operationId: Rain_Intensity
      parameters:
      - name: lat
        in : query
        description: latitude
        required: true
        type: number
        format: double
      - name: lon
        in : query
        description: longitude
        required: true
        type: number
        format: double
      - name: unav
        in : query
        description: unavailability
        required: true
        type: number
        format: double
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OkResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"		
   
  /clima/Nwet:
    # our controller name
    x-swagger-router-controller: propa
    get:
      description: Wet term of refraction coindex
      operationId: Nwet
      parameters:
      - name: lat
        in : query
        description: latitude
        required: true
        type: number
        format: double
      - name: lon
        in : query
        description: longitude
        required: true
        type: number
        format: double
			# define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OkResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /clima/Rain_height:
    # our controller name
    x-swagger-router-controller: propa
    get:
      description: Rain height (km)
      operationId: Rain_height
      parameters:
      - name: lat
        in : query
        description: latitude
        required: true
        type: number
        format: double
      - name: lon
        in : query
        description: longitude
        required: true
        type: number
        format: double
			# define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OkResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  
 
  /clima/TCC:
    # our controller name
    x-swagger-router-controller: propa
    get:
      description: Total Columnar Content of liquid water (kg/m2) exceeded during p % of an average year
      operationId: TCC
      parameters:
      - name: lat
        in : query
        description: latitude
        required: true
        type: number
        format: double
      - name: lon
        in : query
        description: longitude
        required: true
        type: number
        format: double
      - name: unav
        in : query
        description: unavailability
        required: true
        type: number
        format: double
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OkResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"	
            
  /clima/WVC:
    # our controller name
    x-swagger-router-controller: propa
    get:
      description: Annual Surface Water Vapour density (g/m3)
      operationId: WVC
      parameters:
      - name: lat
        in : query
        description: latitude
        required: true
        type: number
        format: double
      - name: lon
        in : query
        description: longitude
        required: true
        type: number
        format: double

      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OkResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /clima/iwvc:
    # our controller name
    x-swagger-router-controller: propa
    get:
      description: Annual Integrated Water Vapour Content (kg/m2) exceeded during p % of an average year
      operationId: iwvc
      parameters:
      - name: lat
        in : query
        description: latitude
        required: true
        type: number
        format: double
      - name: lon
        in : query
        description: longitude
        required: true
        type: number
        format: double
      - name: unav
        in : query
        description: unavailability
        required: true
        type: number
        format: double
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OkResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"	

  /clima/Temperature:
    # our controller name
    x-swagger-router-controller: propa
    get:
      description: Temperature (째K)
      operationId: Temperature
      parameters:
      - name: lat
        in : query
        description: latitude
        required: true
        type: number
        format: double
      - name: lon
        in : query
        description: longitude
        required: true
        type: number
        format: double

      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OkResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /clima/Tmr:
    # our controller name
    x-swagger-router-controller: propa
    get:
      description: TMR (째K)
      operationId: Tmr
      parameters:
      - name: surft
        in : query
        description: Surface temperature (째K)
        required: true
        type: number
        format: double


      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OkResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        
  /clima/Tnoise:
    # our controller name
    x-swagger-router-controller: propa
    get:
      description: Sky noise temperature
      operationId: Tnoise
      parameters:
      - name: TAtt
        in : query
        description: Total attenuation except scintillation (dB)
        required: true
        type: number
        format: double
      - name: MRtemp
        in : query
        description: Mean radiating temperature (째K)
        required: true
        type: number
        format: double		
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OkResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  OkResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
